    # Generated by Django 3.2.4 on 2021-06-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique='True', verbose_name='사용자 이메일')),
                ('name', models.CharField(blank=True, max_length=10, verbose_name='사용자 이름')),
                ('password', models.CharField(max_length=20, verbose_name='비밀 번호')),
                ('phone_number', models.CharField(max_length=11, verbose_name='핸드폰 번호')),
            ],
        ),
    ]
