# Generated by Django 3.2.4 on 2021-06-15 15:09

import account.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=20, validators=[account.validators.validate_name], verbose_name='이름'),
        ),
    ]
