# Generated by Django 3.1.7 on 2021-06-21 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0010_auto_20210621_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListedCompany',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=40, null=True)),
                ('updated', models.DateField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StocksOfInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(blank=True, null=True)),
                ('company_code', models.ForeignKey(blank=True, db_column='company_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='autostock.listedcompany')),
                ('user_id', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='account.user')),
            ],
        ),
        migrations.CreateModel(
            name='DailyTradingInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('open', models.BigIntegerField(blank=True, null=True)),
                ('high', models.BigIntegerField(blank=True, null=True)),
                ('low', models.BigIntegerField(blank=True, null=True)),
                ('close', models.BigIntegerField(blank=True, null=True)),
                ('diff', models.BigIntegerField(blank=True, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('company_code', models.ForeignKey(blank=True, db_column='company_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='autostock.listedcompany')),
            ],
        ),
    ]
